version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


  caloriefyme:
    image: putlurusurya/caloriefyme:1.0
    restart: always
    container_name: caloriefyme
    ports:
      - 8080:8080
    environment:
      FLASK_ENV_URL: http://172.17.0.1:5000

  flaskapp:
    image: putlurusurya/flaskapp:1.0
    restart: always
    container_name: flaskapp
    ports:
      - 5000:5000